on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  node:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: checkout
    steps:
    - id: node-version
      run:
        pwd
        ls -lah
        which node
    - id: create-foo
      run: echo "test=hello" >> foo.txt
  python:
    runs-on: ubuntu-latest
    container:
      image: python:3
    needs: node
    steps:
    -
      run:
        ls -lah
        python --version
