name: Multi Stage
on: [push]
jobs:

  checkout:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

  node:
    runs-on: docker
    container:
      image: node:20
    steps:
      - name: Current directory path
        run: pwd
      - name: Node version
        run: node --version
      - name: create foo
        run: echo "test=hello" >> foo.txt

  python:
    runs-on: docker
    container:
      image: python:3
    needs: node
    steps:
    -
      run:
        ls -lah
        python --version